version: '2'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost